name: main

on:  
  pull_request_target:
    branches : [ main ]
    types: [ closed ]

jobs:
  Release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore
      run: dotnet restore --verbosity minimal
    - name: Build
      run: dotnet build --no-restore --verbosity minimal --configuration Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release
    - name: Pack
      run: dotnet pack --no-build --verbosity normal --configuration Release
    - name: Push
      run: dotnet nuget push */bin/Release/*.nupkg --skip-duplicate --api-key $NUGET_AUTH_TOKEN --source https://api.nuget.org/v3/index.json
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}
